# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velodyne.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='velodyne.proto',
  package='velodyne',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0evelodyne.proto\x12\x08velodyne\"-\n\x0eVelodynePacket\x12\r\n\x05stamp\x18\x01 \x02(\x01\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\"H\n\x0cVelodyneScan\x12\r\n\x05stamp\x18\x01 \x02(\x01\x12)\n\x07packets\x18\x02 \x03(\x0b\x32\x18.velodyne.VelodynePacket\"\xa5\x02\n\x12VelodyneDriverConf\x12\r\n\x05model\x18\x01 \x02(\t\x12\x0b\n\x03rpm\x18\x02 \x01(\x01\x12\x10\n\x08npackets\x18\x03 \x01(\x05\x12%\n\x16timestamp_first_packet\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x0c\n\x04pcap\x18\x05 \x01(\t\x12\x11\n\tcut_angle\x18\x06 \x01(\x01\x12\x0c\n\x04port\x18\x07 \x01(\x05\x12\x11\n\tdevice_ip\x18\x08 \x02(\t\x12\x17\n\x08gps_time\x18\t \x01(\x08:\x05\x66\x61lse\x12\x18\n\tread_once\x18\n \x01(\x08:\x05\x66\x61lse\x12\x18\n\tread_fast\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0crepeat_delay\x18\x0c \x01(\x01:\x01\x30\x12\x12\n\ntopic_name\x18\r \x02(\t\"f\n\x0bPointXYZIRT\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x12\x14\n\tintensity\x18\x04 \x01(\x02:\x01\x30\x12\x0f\n\x04ring\x18\x05 \x01(\x02:\x01\x30\x12\x0f\n\x04time\x18\x06 \x01(\x02:\x01\x30\"A\n\nPointCloud\x12\r\n\x05stamp\x18\x01 \x02(\x01\x12$\n\x05point\x18\x02 \x03(\x0b\x32\x15.velodyne.PointXYZIRT\"\x95\x01\n\x16VelodynePointCloudConf\x12\r\n\x05model\x18\x01 \x02(\t\x12\x13\n\x0b\x63\x61libration\x18\x02 \x02(\t\x12\x11\n\tmax_range\x18\x03 \x02(\x01\x12\x11\n\tmin_range\x18\x04 \x02(\x01\x12\x17\n\x0fscan_topic_name\x18\x05 \x02(\t\x12\x18\n\x10\x63loud_topic_name\x18\x06 \x02(\t'
)




_VELODYNEPACKET = _descriptor.Descriptor(
  name='VelodynePacket',
  full_name='velodyne.VelodynePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='velodyne.VelodynePacket.stamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='velodyne.VelodynePacket.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=73,
)


_VELODYNESCAN = _descriptor.Descriptor(
  name='VelodyneScan',
  full_name='velodyne.VelodyneScan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='velodyne.VelodyneScan.stamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packets', full_name='velodyne.VelodyneScan.packets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=147,
)


_VELODYNEDRIVERCONF = _descriptor.Descriptor(
  name='VelodyneDriverConf',
  full_name='velodyne.VelodyneDriverConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='velodyne.VelodyneDriverConf.model', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rpm', full_name='velodyne.VelodyneDriverConf.rpm', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='npackets', full_name='velodyne.VelodyneDriverConf.npackets', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_first_packet', full_name='velodyne.VelodyneDriverConf.timestamp_first_packet', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pcap', full_name='velodyne.VelodyneDriverConf.pcap', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cut_angle', full_name='velodyne.VelodyneDriverConf.cut_angle', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='velodyne.VelodyneDriverConf.port', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_ip', full_name='velodyne.VelodyneDriverConf.device_ip', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gps_time', full_name='velodyne.VelodyneDriverConf.gps_time', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_once', full_name='velodyne.VelodyneDriverConf.read_once', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_fast', full_name='velodyne.VelodyneDriverConf.read_fast', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeat_delay', full_name='velodyne.VelodyneDriverConf.repeat_delay', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic_name', full_name='velodyne.VelodyneDriverConf.topic_name', index=12,
      number=13, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=443,
)


_POINTXYZIRT = _descriptor.Descriptor(
  name='PointXYZIRT',
  full_name='velodyne.PointXYZIRT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='velodyne.PointXYZIRT.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='velodyne.PointXYZIRT.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='velodyne.PointXYZIRT.z', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='velodyne.PointXYZIRT.intensity', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ring', full_name='velodyne.PointXYZIRT.ring', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='velodyne.PointXYZIRT.time', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=547,
)


_POINTCLOUD = _descriptor.Descriptor(
  name='PointCloud',
  full_name='velodyne.PointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='velodyne.PointCloud.stamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='velodyne.PointCloud.point', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=614,
)


_VELODYNEPOINTCLOUDCONF = _descriptor.Descriptor(
  name='VelodynePointCloudConf',
  full_name='velodyne.VelodynePointCloudConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='velodyne.VelodynePointCloudConf.model', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='calibration', full_name='velodyne.VelodynePointCloudConf.calibration', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_range', full_name='velodyne.VelodynePointCloudConf.max_range', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_range', full_name='velodyne.VelodynePointCloudConf.min_range', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scan_topic_name', full_name='velodyne.VelodynePointCloudConf.scan_topic_name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cloud_topic_name', full_name='velodyne.VelodynePointCloudConf.cloud_topic_name', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=766,
)

_VELODYNESCAN.fields_by_name['packets'].message_type = _VELODYNEPACKET
_POINTCLOUD.fields_by_name['point'].message_type = _POINTXYZIRT
DESCRIPTOR.message_types_by_name['VelodynePacket'] = _VELODYNEPACKET
DESCRIPTOR.message_types_by_name['VelodyneScan'] = _VELODYNESCAN
DESCRIPTOR.message_types_by_name['VelodyneDriverConf'] = _VELODYNEDRIVERCONF
DESCRIPTOR.message_types_by_name['PointXYZIRT'] = _POINTXYZIRT
DESCRIPTOR.message_types_by_name['PointCloud'] = _POINTCLOUD
DESCRIPTOR.message_types_by_name['VelodynePointCloudConf'] = _VELODYNEPOINTCLOUDCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VelodynePacket = _reflection.GeneratedProtocolMessageType('VelodynePacket', (_message.Message,), {
  'DESCRIPTOR' : _VELODYNEPACKET,
  '__module__' : 'velodyne_pb2'
  # @@protoc_insertion_point(class_scope:velodyne.VelodynePacket)
  })
_sym_db.RegisterMessage(VelodynePacket)

VelodyneScan = _reflection.GeneratedProtocolMessageType('VelodyneScan', (_message.Message,), {
  'DESCRIPTOR' : _VELODYNESCAN,
  '__module__' : 'velodyne_pb2'
  # @@protoc_insertion_point(class_scope:velodyne.VelodyneScan)
  })
_sym_db.RegisterMessage(VelodyneScan)

VelodyneDriverConf = _reflection.GeneratedProtocolMessageType('VelodyneDriverConf', (_message.Message,), {
  'DESCRIPTOR' : _VELODYNEDRIVERCONF,
  '__module__' : 'velodyne_pb2'
  # @@protoc_insertion_point(class_scope:velodyne.VelodyneDriverConf)
  })
_sym_db.RegisterMessage(VelodyneDriverConf)

PointXYZIRT = _reflection.GeneratedProtocolMessageType('PointXYZIRT', (_message.Message,), {
  'DESCRIPTOR' : _POINTXYZIRT,
  '__module__' : 'velodyne_pb2'
  # @@protoc_insertion_point(class_scope:velodyne.PointXYZIRT)
  })
_sym_db.RegisterMessage(PointXYZIRT)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUD,
  '__module__' : 'velodyne_pb2'
  # @@protoc_insertion_point(class_scope:velodyne.PointCloud)
  })
_sym_db.RegisterMessage(PointCloud)

VelodynePointCloudConf = _reflection.GeneratedProtocolMessageType('VelodynePointCloudConf', (_message.Message,), {
  'DESCRIPTOR' : _VELODYNEPOINTCLOUDCONF,
  '__module__' : 'velodyne_pb2'
  # @@protoc_insertion_point(class_scope:velodyne.VelodynePointCloudConf)
  })
_sym_db.RegisterMessage(VelodynePointCloudConf)


# @@protoc_insertion_point(module_scope)
